unit MAQUINAS;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  dmodule,Dialogs, DB, IBCustomDataSet, IBTable, DBGridEhGrouping, GridsEh,
  DBGridEh, StdCtrls, DBCtrlsEh, Mask, IBQuery, DBLookupEh, ComCtrls, ExtCtrls,
  DBCtrls, ACBrBase, ACBrEnterTab;

type
  TfrmMAQUINAS = class(TForm)
    ibtbMAQUINAS: TIBTable;
    smlntfldMAQUINASFK_EMPRESAS: TSmallintField;
    smlntfldMAQUINASFK_FILIAIS: TSmallintField;
    smlntfldMAQUINASFK_DEPARTAMENTOS: TSmallintField;
    smlntfldMAQUINASFK_SETORES: TSmallintField;
    smlntfldMAQUINASFK_PROCESSOS: TSmallintField;
    intgrfldMAQUINASPK_MAQUINAS: TIntegerField;
    ibstrngfldMAQUINASDESCRICAO: TIBStringField;
    smlntfldMAQUINASFK_FAMILIAS: TSmallintField;
    smlntfldMAQUINASFK_SITUACAO: TSmallintField;
    intgrfldMAQUINASFK_IMAGEM: TIntegerField;
    intgrfldMAQUINASFK_ANEXOS: TIntegerField;
    ibstrngfldMAQUINASFK_CENTROCUSTO: TIBStringField;
    smlntfldMAQUINASPESO: TSmallintField;
    ibtbMAQUINASPO_CUS_MAN: TIBBCDField;
    ibtbMAQUINASPO_FATURAM: TIBBCDField;
    ibtbMAQUINASPO_MAQ_PAR: TIBBCDField;
    smlntfldMAQUINASVALOR_CRITICIDADE: TSmallintField;
    ibtbMAQUINASTOT_CUSMAN: TIBBCDField;
    ibtbMAQUINASTOT_FATURA: TIBBCDField;
    dtmfldMAQUINASDH_MAQDISPONIVEL: TDateTimeField;
    smlntfldMAQUINASPESO_PRODRUCAO: TSmallintField;
    ibstrngfldMAQUINASPERI_CODIG: TIBStringField;
    tmfldMAQUINASTEMPO_MAXIMO_PARADA: TTimeField;
    intgrfldMAQUINASMTBF: TIntegerField;
    ibstrngfldMAQUINASNRO_PATRIMONIAL: TIBStringField;
    ibstrngfldMAQUINASMAQ_ATIVA: TIBStringField;
    intgrfldMAQUINASACUM_PARA: TIntegerField;
    intgrfldMAQUINASFK_PRODUTOS: TIntegerField;
    dsMAQUINAS: TDataSource;
    edtPK_MAQUINAS: TDBEditEh;
    edtDESCRICAO: TDBEditEh;
    DBCheckBoxEh1: TDBCheckBoxEh;
    edtFK_PRODUTOS: TDBEditEh;
    edtFK_EMPRESAS: TDBEditEh;
    cbbFK_EMPRESAS: TDBLookupComboboxEh;
    edtFK_FILIAIS: TDBEditEh;
    cbbFK_FILIAIS: TDBLookupComboboxEh;
    edtFK_DEPARTAMENTOS: TDBEditEh;
    cbbFK_DEPARTAMENTOS: TDBLookupComboboxEh;
    edtFK_SETORES: TDBEditEh;
    cbbFK_SETORES: TDBLookupComboboxEh;
    edtFK_EMPRESAS1: TDBEditEh;
    cbbFK_EMPRESAS1: TDBLookupComboboxEh;
    dsPROCESSOS: TDataSource;
    dsDEPTOS: TDataSource;
    ibqryEmpresas: TIBQuery;
    intgrfldEmpresasPK_EMPRESA: TIntegerField;
    ibstrngfldEmpresasRAZAOSOCIAL: TIBStringField;
    ibstrngfldEmpresasENDERECO: TIBStringField;
    ibstrngfldEmpresasEND_NUMERO: TIBStringField;
    ibstrngfldEmpresasEND_COMPLEMENTO: TIBStringField;
    intgrfldEmpresasPK_BAIRRO: TIntegerField;
    intgrfldEmpresasPK_CIDADE: TIntegerField;
    intgrfldEmpresasPK_PAIS: TIntegerField;
    ibstrngfldEmpresasTELEFONE: TIBStringField;
    ibstrngfldEmpresasTELEFAX: TIBStringField;
    ibstrngfldEmpresasEMAIL: TIBStringField;
    ibstrngfldEmpresasWEBSITE: TIBStringField;
    ibstrngfldEmpresasCNAE: TIBStringField;
    ibstrngfldEmpresasCNAE2: TIBStringField;
    ibstrngfldEmpresasCNPJ: TIBStringField;
    ibstrngfldEmpresasINSC_ESTADUAL: TIBStringField;
    ibstrngfldEmpresasINSC_MUNICIPAL: TIBStringField;
    ibstrngfldEmpresasCEP: TIBStringField;
    ibstrngfldEmpresasUF: TIBStringField;
    ibstrngfldEmpresasNOMEFANTASIA: TIBStringField;
    smlntfldEmpresasDDD: TSmallintField;
    dsEMPRESA: TDataSource;
    dsFILIAL: TDataSource;
    ibqryFiliais: TIBQuery;
    intgrfldFiliaisPK_EMPRESA: TIntegerField;
    intgrfldFiliaisPK_FILIAL: TIntegerField;
    ibstrngfldFiliaisRAZAOSOCIAL: TIBStringField;
    ibstrngfldFiliaisENDERECO: TIBStringField;
    ibstrngfldFiliaisEND_NUMERO: TIBStringField;
    ibstrngfldFiliaisEND_COMPLEMENTO: TIBStringField;
    intgrfldFiliaisPK_BAIRRO: TIntegerField;
    intgrfldFiliaisPK_CIDADE: TIntegerField;
    intgrfldFiliaisPK_PAIS: TIntegerField;
    ibstrngfldFiliaisTELEFONE: TIBStringField;
    ibstrngfldFiliaisTELEFAX: TIBStringField;
    ibstrngfldFiliaisEMAIL: TIBStringField;
    ibstrngfldFiliaisWEBSITE: TIBStringField;
    ibstrngfldFiliaisCNAE: TIBStringField;
    ibstrngfldFiliaisCNAE2: TIBStringField;
    ibstrngfldFiliaisCNPJ: TIBStringField;
    ibstrngfldFiliaisINSC_ESTADUAL: TIBStringField;
    ibstrngfldFiliaisINSC_MUNICIPAL: TIBStringField;
    ibstrngfldFiliaisCEP: TIBStringField;
    ibstrngfldFiliaisUF: TIBStringField;
    ibstrngfldFiliaisNOMEFANTASIA: TIBStringField;
    smlntfldFiliaisDDD: TSmallintField;
    ibstrngfldFiliaisFK_NATUREZAJURIDICA: TIBStringField;
    ibqryPRIORIDADE: TIBQuery;
    dsPRIORIDADE: TDataSource;
    dsSETORES: TDataSource;
    ibqrySETORES: TIBQuery;
    edtFK_PRIORIDADE: TDBEditEh;
    ibqryPROCESSOS: TIBQuery;
    dsCENTROCUSTO: TDataSource;
    edtFK_PROCESSOS: TDBEditEh;
    edtFK_PROCESSOS1: TDBEditEh;
    edtFK_PROCESSOS2: TDBEditEh;
    edtFK_PROCESSOS3: TDBEditEh;
    edtFK_PROCESSOS4: TDBEditEh;
    edtFK_PRODUTOS1: TDBEditEh;
    edtPESO: TDBEditEh;
    edtFK_PRODUTOS2: TDBEditEh;
    edtFK_PRODUTOS3: TDBEditEh;
    edtFK_PRODUTOS4: TDBEditEh;
    edtFK_PRODUTOS5: TDBEditEh;
    pgc1: TPageControl;
    ts1: TTabSheet;
    dbnvgr1: TDBNavigator;
    cbbFK_CENTROCUSTO: TDBLookupComboboxEh;
    ibqryDEPARTAMENTOS: TIBQuery;
    acbrntrtb1: TACBrEnterTab;
    ibqryCENTROCUSTO: TIBQuery;
    ibstrngfldCENTROCUSTOCC_CODIGO: TIBStringField;
    ibstrngfldCENTROCUSTODESCRICAO: TIBStringField;
    smlntfldCENTROCUSTOPESO: TSmallintField;
    ibstrngfldCENTROCUSTORESPONSAVEL: TIBStringField;
    smlntfldCENTROCUSTOFK_CONTABILCREDITO: TSmallintField;
    smlntfldCENTROCUSTOFK_CONTABILDEBITO: TSmallintField;
    smlntfldCENTROCUSTOFK_EMPRESAS: TSmallintField;
    smlntfldCENTROCUSTOFK_FILIAIS: TSmallintField;
    smlntfldCENTROCUSTOFK_DEPARTAMENTOS: TSmallintField;
    smlntfldCENTROCUSTOFK_SETORES: TSmallintField;
    smlntfldCENTROCUSTOSEQUENCIAL: TSmallintField;
    ibstrngfldCENTROCUSTOCLASSECENTROCUSTO: TIBStringField;
    ibstrngfldCENTROCUSTOACEITAITENS: TIBStringField;
    ibstrngfldCENTROCUSTOTIPOCENTROCUSTO: TIBStringField;
    ts2: TTabSheet;
    ts3: TTabSheet;
    ibqryTAGS: TIBQuery;
    dbgrdh1: TDBGridEh;
    dsTAGS: TDataSource;
    intgrfldTAGSFK_EMPRESAS: TIntegerField;
    intgrfldTAGSFK_FILIAIS: TIntegerField;
    intgrfldTAGSFK_DEPARTAMENTO: TIntegerField;
    intgrfldTAGSFK_SETORES: TIntegerField;
    intgrfldTAGSFK_PROCESSOS: TIntegerField;
    intgrfldTAGSFK_MAQUINAS: TIntegerField;
    intgrfldTAGSPK_TAG: TIntegerField;
    ibstrngfldTAGSDESCRICAO: TIBStringField;
    ibstrngfldTAGSPRODUTOS: TIBStringField;
    ibqryTAGSDATAINICIAL: TDateField;
    intgrfldTAGSFK_CENTROCUSTO: TIntegerField;
    intgrfldTAGSFK_FAMILIAS: TIntegerField;
    intgrfldTAGSFK_PRIORIDADE: TIntegerField;
    ibstrngfldTAGSTAG_MULTIPLO: TIBStringField;
    ibstrngfldTAGSTAG_PARADO: TIBStringField;
    intgrfldTAGSFK_IMAGEM: TIntegerField;
    smlntfldTAGSTAG_PESO: TSmallintField;
    intgrfldTAGSFK_ANEXOS: TIntegerField;
    smlntfldTAGSVALORCRITICIDADE: TSmallintField;
    smlntfldTAGSDIAS_RETRABALHO: TSmallintField;
    ibstrngfldTAGSAFETA_PRODUCAO: TIBStringField;
    tmfldTAGSHORA_DISPONIVEL: TTimeField;
    tmfldTAGSTEMPO_MAXIMO_PARADA: TTimeField;
    intgrfldTAGSMTBF: TIntegerField;
    ibqryTAGSTAG_DATA: TDateField;
    intgrfldTAGSFK_HISTORICOS: TIntegerField;
    ibqryEQUIPAMENTOS: TIBQuery;
    dsEQUIPAMENTOS: TDataSource;
    dbgrdh2: TDBGridEh;
    ibqryMAQ_PECAS: TIBQuery;
    intgrfldMAQ_PECASPK_PRODUTOS: TIntegerField;
    smlntfldMAQ_PECASFK_SECOES: TSmallintField;
    smlntfldMAQ_PECASFK_GRUPOS: TSmallintField;
    smlntfldMAQ_PECASFK_SUBGRUPOS: TSmallintField;
    smlntfldMAQ_PECASPK_UNIDVENDA: TSmallintField;
    ibstrngfldMAQ_PECASDESCRICAO: TIBStringField;
    ibstrngfldMAQ_PECASPRODUTOATIVO: TIBStringField;
    ibstrngfldMAQ_PECASFLAG_PROD: TIBStringField;
    ibqryMAQ_PECASQUANT_UNIDVENDA: TIBBCDField;
    ibstrngfldMAQ_PECASOPE_INC: TIBStringField;
    dtmfldMAQ_PECASDTHR_INC: TDateTimeField;
    ibstrngfldMAQ_PECASOPE_ALT: TIBStringField;
    dtmfldMAQ_PECASDTHR_ALT: TDateTimeField;
    intgrfldMAQ_PECASPK_PROD_FAMILIA: TIntegerField;
    ibstrngfldMAQ_PECASRESUMIDA: TIBStringField;
    ibstrngfldMAQ_PECASCODBARRA: TIBStringField;
    ibstrngfldMAQ_PECASTEMVALIDADE: TIBStringField;
    ibstrngfldMAQ_PECASCONTROLAVALIDADE: TIBStringField;
    ibstrngfldMAQ_PECASCONTROLALOTE: TIBStringField;
    ibqryMAQ_PECASVALIDADEPRODUTO: TIBBCDField;
    ibstrngfldMAQ_PECASTIPOVALIDADE: TIBStringField;
    ibstrngfldMAQ_PECASMESANOREFERENCIA: TIBStringField;
    ibstrngfldMAQ_PECASEMITEETIQUETABARRA: TIBStringField;
    ibstrngfldMAQ_PECASEMITEETIQUETAGONDOLA: TIBStringField;
    ibstrngfldMAQ_PECASEMITEETIQUEEMBALAGEM: TIBStringField;
    ibqryMAQ_PECASPESOLIQUIDO: TIBBCDField;
    ibqryMAQ_PECASPESOBRUTO: TIBBCDField;
    ibqryMAQ_PECASMEDIDALARGURA: TIBBCDField;
    ibqryMAQ_PECASMEDIDAALTURA: TIBBCDField;
    ibqryMAQ_PECASMEDIDAPROFUNDIDADE: TIBBCDField;
    ibstrngfldMAQ_PECASTEMVASILHAME: TIBStringField;
    intgrfldMAQ_PECASPK_VASILHAME: TIntegerField;
    ibstrngfldMAQ_PECASPRODUTOCONTROLADO: TIBStringField;
    ibstrngfldMAQ_PECASCLASSIFICACAOFISCAL: TIBStringField;
    ibstrngfldMAQ_PECASSITUACAOTRIBUTARIA: TIBStringField;
    ibstrngfldMAQ_PECASCODIGONCM: TIBStringField;
    ibqryMAQ_PECASALICOTAICMS: TIBBCDField;
    ibqryMAQ_PECASALICOTAICMSSUBST: TIBBCDField;
    ibqryMAQ_PECASALICOTAIPI: TIBBCDField;
    ibqryMAQ_PECASALICOTAISSQN: TIBBCDField;
    ibqryMAQ_PECASALICOTAFRETE: TIBBCDField;
    ibqryMAQ_PECASALICOTAREDBASECALCULO: TIBBCDField;
    ibqryMAQ_PECASMEDIDACUBAGEM: TIBBCDField;
    ibstrngfldMAQ_PECASPRODUTOFRACIONADO: TIBStringField;
    ibstrngfldMAQ_PECASPRODUTOREFERENCIA: TIBStringField;
    ibqryMAQ_PECASALICOTABASECALCULO: TIBBCDField;
    ibstrngfldMAQ_PECASPRODUTOCOMPOSTO: TIBStringField;
    ibqryMAQ_PECASVALORFRETE: TIBBCDField;
    smlntfldMAQ_PECASTIPOPRODUTO: TSmallintField;
    intgrfldMAQ_PECASPK_EMBALAGEM: TIntegerField;
    ibqryMAQ_PECASQUANTIDADEMINIMA: TIBBCDField;
    ibstrngfldMAQ_PECASSITUACAOPRODUTO: TIBStringField;
    smlntfldMAQ_PECASFK_TIPOENTRADAPADRAO: TSmallintField;
    smlntfldMAQ_PECASFK_TIPOSAIDAPADRAO: TSmallintField;
    dtmfldMAQ_PECASCUSTO_ULTIMOCALCULO: TDateTimeField;
    smlntfldMAQ_PECASFK_CTACONTABILCREDITO: TSmallintField;
    smlntfldMAQ_PECASFK_CTACONTABILDEBITO: TSmallintField;
    ibstrngfldMAQ_PECASFK_CENTROCUSTO: TIBStringField;
    ibstrngfldMAQ_PECASFK_TIPOAPROPRIACAO: TIBStringField;
    ibqryMAQ_PECASALICOTA_COMISSAO: TIBBCDField;
    ibstrngfldMAQ_PECASTIPORASTREABILIDADE: TIBStringField;
    ibstrngfldMAQ_PECASPRODUTOIMPORTADO: TIBStringField;
    smlntfldMAQ_PECASFK_CQ_TIPO: TSmallintField;
    smlntfldMAQ_PECASCQ_NOTAMINIMA: TSmallintField;
    smlntfldMAQ_PECASCQ_QUANTPRODUCAO: TSmallintField;
    smlntfldMAQ_PECASPRAZOENTREGA: TSmallintField;
    ibqryMAQ_PECASLOTEECONOMICO: TIBBCDField;
    ibqryMAQ_PECASLOTEMINIMO: TIBBCDField;
    smlntfldMAQ_PECASFK_TIPOCARGA: TSmallintField;
    dsMAQ_PECAS: TDataSource;
    dbgrdh3: TDBGridEh;
    procedure FormCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frmMAQUINAS: TfrmMAQUINAS;

implementation

{$R *.dfm}

procedure TfrmMAQUINAS.FormCreate(Sender: TObject);
begin
ibqryDEPARTAMENTOS.Open;
ibtbMAQUINAS.Open;
ibqryEmpresas.Open;
ibqryFiliais.Open;
ibqryPROCESSOS.Open;
ibqryPRIORIDADE.Open;
ibqrySETORES.Open;
ibqryCENTROCUSTO.Open;
end;

end.
